/*
 * Copyright 2007 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package javax.xml.ws.soap;

import java.lang.annotation.Documented;
import java.lang.annotation.Target;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import javax.xml.ws.spi.WebServiceFeatureAnnotation;

/**
 * {@add The definition of this annotation is only partly defined in this release of JAX-WS as
 * there is no standard way to convey its meaning via a WSDL.
 * A future release of JAX-WS will provide that standard mechanism to convey the meaning
 * of this annotation via WSDL.  An implementation MAY indicate via WSDL, in a non-standard
 * way, the use of this annotation.  The runtime behavior of this annotation is well-defined
 * in this release of JAX-WS, however, unless an implementation specifies that addressing is
 * being used in a proprietary way in the WSDL, a JAX-WS client MUST explicitly enable addressing via
 * the }{@link AddressingFeature} {@add if Addressing is to be used.}
 * <p>
 * This feature represents the use of WS-Addressing with either
 * the SOAP 1.1/HTTP or SOAP 1.2/HTTP binding.  Using this feature
 * with any other binding is NOT required.
 * <p>
 * {@delete Enabling this feature will result in the
 * <code>wsaw:UsingAddressing</code> element being added to the
 * <code>wsdl:Binding</code> for
 * the endpoint and in the runtime being capable of responding to
 * WS-Addressing headers.}
 * <p>
 * The following describes the affects of this feature with respect
 * to be enabled or disabled:
 * <ul>
 *  <li> ENABLED: In this Mode, Addressing will be enabled.
 *       {@delete If there is not a WSDL associated with the Endpoint and
 *       a WSDL is to be generated, it MUST be generated with the
 *       wsaw:UsingAddressing element.} At runtime, Addressing headers
 *       MUST be consumed by the receiver and generated by the
 *       sender even if the WSDL declares otherwise. The
 *       mustUnderstand="0" attribute MUST be used on the Addressing
 *       headers. 
 *  <li> DISABLED: In this Mode, Addressing will be disabled
 *       even if an associated WSDL specifies otherwise. At runtime,
 *       Addressing headers MUST NOT be used.  This may be used when an application
 *       implementor has implemented Addressing themselves and thus do not want
 *       the JAX-WS implementation to provide Addressing processing.  {@add If an application
 *       has implemented Addressing themselves, they MUST explicitly disable this feature.
*        Not doing so may break compatability with future versions of JAX-WS.}
 * </ul>
 * <p>
 * The {@link #required} property can be used to
 * specify if {@delete the <code>required</code> attribute on the
 * <code>wsaw:UsingAddressing</code> element should
 * be <code>true</code> or <code>false</code>} {@add Addressing headers MUST
 * be present on incoming messages.  If this property is <code>false</code>
 * incoming messages MAY include Addressing headers}.  By default the
 * <code>required</code> property is <code>false</code>.
 * <p>
 * See <a href="http://www.w3.org/TR/2006/REC-ws-addr-core-20060509/">Web Services Addressing - Core</a>
 * {@add and <a href="http://www.w3.org/TR/2006/REC-ws-addr-soap-20060509/">Web Services Addressing 1.0 - SOAP Binding</a> }
 * for more information on WS-Addressing.
 * {@delete </a> for more information on <code>wsaw:UsingAddressing</code>.}
 * {@delete See <a href="http://www.w3.org/TR/2006/CR-ws-addr-wsdl-20060529/#indicatinguse/">WS-Addressing - WSDL 1.0
 * </a> for more information on <code>wsaw:UsingAddressing</code>.}
 *
 * @since JAX-WS 2.1
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@WebServiceFeatureAnnotation(id=AddressingFeature.ID,bean=AddressingFeature.class)
public @interface Addressing {
    /**
     * Specifies if this feature is enabled or disabled.
     */
    boolean enabled() default true;
    
    /**
     * {@add This is a placeholder property to be fully defined in a future version
     * of JAX-WS.  However, an implementation MUST use this property to determine 
     * if Addressing headers MUST
     * be present on incoming messages.}{@delete the value of the
     * <code>wsdl:required</code> attribute on
     * <code>wsaw:UsingAddressing</code> element in the WSDL}.  {@add An implementation
     * MAY indicate via WSDL that use of Addressing is required, but it would do so in
     * a proprietary way.  A future version of JAX-WS will define the standard way to
     * indicate this requiement.}
     */
    boolean required() default false;
}
